import { useTranslation } from 'react-i18next';
import { AnimalCase, Campaign, Partner, Volunteer, CommunityPost } from '@/types';

// Hook that returns mock data with translations applied
export function useTranslatedMockData() {
  const { t } = useTranslation();

  const mockCases: AnimalCase[] = [
    {
      id: '1',
      title: t('mockData.cases.case1.title'),
      description: t('mockData.cases.case1.description'),
      story: t('mockData.cases.case1.story'),
      images: [
        'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
        'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
        'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
      ],
      status: 'urgent',
      species: 'dog',
      location: { city: t('cities.sofia'), neighborhood: t('neighborhoods.center') },
      fundraising: { current: 320, goal: 500, currency: 'EUR' },
      updates: [
        { id: 'u1', date: '2024-01-15', title: t('mockData.cases.case1.updates.u1.title'), description: t('mockData.cases.case1.updates.u1.description'), type: 'milestone' },
        { id: 'u2', date: '2024-01-16', title: t('mockData.cases.case1.updates.u2.title'), description: t('mockData.cases.case1.updates.u2.description'), type: 'medical' },
        { id: 'u3', date: '2024-01-18', title: t('mockData.cases.case1.updates.u3.title'), description: t('mockData.cases.case1.updates.u3.description'), type: 'success' },
      ],
      createdAt: '2024-01-15',
    },
    {
      id: '2',
      title: t('mockData.cases.case2.title'),
      description: t('mockData.cases.case2.description'),
      story: t('mockData.cases.case2.story'),
      images: [
        'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
        'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800',
      ],
      status: 'critical',
      species: 'cat',
      location: { city: t('cities.plovdiv'), neighborhood: t('neighborhoods.kapana') },
      fundraising: { current: 450, goal: 800, currency: 'EUR' },
      updates: [
        { id: 'u1', date: '2024-01-14', title: t('mockData.cases.case2.updates.u1.title'), description: t('mockData.cases.case2.updates.u1.description'), type: 'medical' },
        { id: 'u2', date: '2024-01-15', title: t('mockData.cases.case2.updates.u2.title'), description: t('mockData.cases.case2.updates.u2.description'), type: 'medical' },
      ],
      createdAt: '2024-01-14',
    },
    {
      id: '3',
      title: t('mockData.cases.case3.title'),
      description: t('mockData.cases.case3.description'),
      story: t('mockData.cases.case3.story'),
      images: [
        'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=800',
        'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
      ],
      status: 'adopted',
      species: 'dog',
      location: { city: t('cities.burgas'), neighborhood: t('neighborhoods.seaGarden') },
      fundraising: { current: 600, goal: 600, currency: 'EUR' },
      updates: [
        { id: 'u1', date: '2023-07-10', title: t('mockData.cases.case3.updates.u1.title'), description: t('mockData.cases.case3.updates.u1.description'), type: 'milestone' },
        { id: 'u2', date: '2023-09-15', title: t('mockData.cases.case3.updates.u2.title'), description: t('mockData.cases.case3.updates.u2.description'), type: 'success' },
        { id: 'u3', date: '2024-01-10', title: t('mockData.cases.case3.updates.u3.title'), description: t('mockData.cases.case3.updates.u3.description'), type: 'success' },
      ],
      createdAt: '2023-07-10',
    },
    {
      id: '4',
      title: t('mockData.cases.case4.title'),
      description: t('mockData.cases.case4.description'),
      story: t('mockData.cases.case4.story'),
      images: [
        'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
        'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
      ],
      status: 'recovering',
      species: 'dog',
      location: { city: t('cities.varna'), neighborhood: t('neighborhoods.asparuhovo') },
      fundraising: { current: 180, goal: 1000, currency: 'EUR' },
      updates: [
        { id: 'u1', date: '2024-01-17', title: t('mockData.cases.case4.updates.u1.title'), description: t('mockData.cases.case4.updates.u1.description'), type: 'milestone' },
        { id: 'u2', date: '2024-01-18', title: t('mockData.cases.case4.updates.u2.title'), description: t('mockData.cases.case4.updates.u2.description'), type: 'update' },
      ],
      createdAt: '2024-01-17',
    },
  ];

  const mockCampaigns: Campaign[] = [
    {
      id: 'c1',
      title: t('mockData.campaigns.c1.title'),
      description: t('mockData.campaigns.c1.description'),
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
      goal: 50,
      current: 23,
      unit: t('mockData.campaigns.units.homes'),
      endDate: '2024-03-01',
    },
    {
      id: 'c2',
      title: t('mockData.campaigns.c2.title'),
      description: t('mockData.campaigns.c2.description'),
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=800',
      goal: 100,
      current: 67,
      unit: t('mockData.campaigns.units.surgeries'),
    },
    {
      id: 'c3',
      title: t('mockData.campaigns.c3.title'),
      description: t('mockData.campaigns.c3.description'),
      image: 'https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=800',
      goal: 10000,
      current: 4250,
      unit: 'EUR',
    },
    {
      id: 'c4',
      title: t('mockData.campaigns.c4.title'),
      description: t('mockData.campaigns.c4.description'),
      image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800',
      goal: 1000,
      current: 412,
      unit: t('mockData.campaigns.units.meals'),
      endDate: '2024-02-15',
    },
    {
      id: 'c5',
      title: t('mockData.campaigns.c5.title'),
      description: t('mockData.campaigns.c5.description'),
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      goal: 5000,
      current: 2100,
      unit: 'EUR',
      endDate: '2024-04-01',
    },
    {
      id: 'c6',
      title: t('mockData.campaigns.c6.title'),
      description: t('mockData.campaigns.c6.description'),
      image: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
      goal: 200,
      current: 89,
      unit: t('mockData.campaigns.units.vaccinations'),
    },
  ];

  const mockPartners: Partner[] = [
    {
      id: 'p1',
      name: 'PetMart Bulgaria',
      logo: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=200',
      contribution: t('mockData.partners.p1.contribution'),
      description: t('mockData.partners.p1.description'),
      type: 'pet-shop',
      website: 'https://petmart.bg',
      since: '2021',
      animalsHelped: 340,
      totalContributed: 25000,
      featured: true,
    },
    {
      id: 'p2',
      name: 'Royal Canin BG',
      logo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=200',
      contribution: t('mockData.partners.p2.contribution'),
      description: t('mockData.partners.p2.description'),
      type: 'food-brand',
      website: 'https://royalcanin.bg',
      since: '2020',
      animalsHelped: 450,
      totalContributed: 48000,
      featured: true,
    },
    {
      id: 'p3',
      name: 'VetCare Sofia',
      logo: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=200',
      contribution: t('mockData.partners.p3.contribution'),
      description: t('mockData.partners.p3.description'),
      type: 'veterinary',
      website: 'https://vetcare.bg',
      since: '2019',
      animalsHelped: 820,
      totalContributed: 35000,
    },
    {
      id: 'p4',
      name: t('mockData.partners.p4.name'),
      logo: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=200',
      contribution: t('mockData.partners.p4.contribution'),
      description: t('mockData.partners.p4.description'),
      type: 'sponsor',
      website: 'https://animalfriends.bg',
      since: '2018',
      animalsHelped: 1200,
      totalContributed: 180000,
      featured: true,
    },
    {
      id: 'p5',
      name: t('mockData.partners.p5.name'),
      logo: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=200',
      contribution: t('mockData.partners.p5.contribution'),
      description: t('mockData.partners.p5.description'),
      type: 'pet-shop',
      since: '2022',
      animalsHelped: 150,
      totalContributed: 12000,
    },
    {
      id: 'p6',
      name: 'Pro Plan Bulgaria',
      logo: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=200',
      contribution: t('mockData.partners.p6.contribution'),
      description: t('mockData.partners.p6.description'),
      type: 'food-brand',
      website: 'https://proplan.bg',
      since: '2021',
      animalsHelped: 280,
      totalContributed: 32000,
    },
    {
      id: 'p7',
      name: t('mockData.partners.p7.name'),
      logo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200',
      contribution: t('mockData.partners.p7.contribution'),
      description: t('mockData.partners.p7.description'),
      type: 'veterinary',
      website: 'https://drpetrov.bg',
      since: '2020',
      animalsHelped: 560,
      totalContributed: 75000,
      featured: true,
    },
    {
      id: 'p8',
      name: t('mockData.partners.p8.name'),
      logo: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=200',
      contribution: t('mockData.partners.p8.contribution'),
      description: t('mockData.partners.p8.description'),
      type: 'sponsor',
      since: '2023',
      animalsHelped: 200,
      totalContributed: 15000,
    },
  ];

  const mockVolunteers: Volunteer[] = [
    {
      id: 'v1',
      name: t('mockData.volunteers.v1.name'),
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
      bio: t('mockData.volunteers.v1.bio'),
      location: t('cities.sofia'),
      rating: 4.9,
      memberSince: '2019',
      isTopVolunteer: true,
      badges: [t('mockData.badges.monthlyHero'), t('mockData.badges.rescueChampion'), t('mockData.badges.animals100')],
      badgesMobile: [t('mockData.badgesMobile.monthlyHero'), t('mockData.badgesMobile.rescueChampion'), t('mockData.badgesMobile.animals100')],
      stats: {
        animalsHelped: 127,
        adoptions: 45,
        campaigns: 23,
        donationsReceived: 8500,
        hoursVolunteered: 520,
      },
    },
    {
      id: 'v2',
      name: t('mockData.volunteers.v2.name'),
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      bio: t('mockData.volunteers.v2.bio'),
      location: t('cities.plovdiv'),
      rating: 4.8,
      memberSince: '2020',
      isTopVolunteer: true,
      badges: [t('mockData.badges.fosterHero'), t('mockData.badges.medicalSupport'), t('mockData.badges.topDonor')],
      badgesMobile: [t('mockData.badgesMobile.fosterHero'), t('mockData.badgesMobile.medicalSupport'), t('mockData.badgesMobile.topDonor')],
      stats: {
        animalsHelped: 89,
        adoptions: 32,
        campaigns: 15,
        donationsReceived: 4200,
        hoursVolunteered: 340,
      },
    },
    {
      id: 'v3',
      name: t('mockData.volunteers.v3.name'),
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
      bio: t('mockData.volunteers.v3.bio'),
      location: t('cities.sofia'),
      rating: 4.9,
      memberSince: '2018',
      isTopVolunteer: true,
      badges: [t('mockData.badges.trainingExpert'), t('mockData.badges.communityLeader'), t('mockData.badges.animals200')],
      badgesMobile: [t('mockData.badgesMobile.trainingExpert'), t('mockData.badgesMobile.communityLeader'), t('mockData.badgesMobile.animals200')],
      stats: {
        animalsHelped: 234,
        adoptions: 89,
        campaigns: 34,
        donationsReceived: 12300,
        hoursVolunteered: 890,
      },
    },
  ];

  const mockCommunityPosts: CommunityPost[] = [
    {
      id: 'p1',
      author: {
        id: 'v1',
        name: t('mockData.volunteers.v1.name'),
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
        isVolunteer: true,
      },
      content: t('mockData.posts.p1.content'),
      image: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
      likes: 124,
      comments: 23,
      timeAgo: t('time.hoursAgo', { count: 2 }),
      createdAt: '2026-01-12T10:00:00Z',
    },
    {
      id: 'p2',
      author: {
        id: 'v3',
        name: t('mockData.volunteers.v3.name'),
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
        isVolunteer: true,
      },
      content: t('mockData.posts.p2.content'),
      image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
      likes: 256,
      comments: 45,
      timeAgo: t('time.hoursAgo', { count: 5 }),
      createdAt: '2026-01-12T07:00:00Z',
    },
    {
      id: 'p3',
      author: {
        id: 'u1',
        name: t('mockData.users.u1.name'),
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200',
        isVolunteer: false,
      },
      content: t('mockData.posts.p3.content'),
      likes: 15,
      comments: 28,
      timeAgo: t('time.daysAgo', { count: 1 }),
      createdAt: '2026-01-11T14:00:00Z',
    },
  ];

  return {
    mockCases,
    mockCampaigns,
    mockPartners,
    mockVolunteers,
    mockCommunityPosts,
  };
}
